[project]
name = "audiotools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.72.0",
    "gradio>=5.49.1",
    "requests>=2.32.5",
]
